name: ARLON CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Deploying to Hetzner VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Loyha papkasiga kiramiz (agar papka bo'lsa)
            cd ~/ARLON || mkdir -p ~/ARLON && cd ~/ARLON
            
            # Agar papka yangi bo'lsa va git sozlanmagan bo'lsa deb tekshiramiz
            if [ ! -d ".git" ]; then
              git clone https://github.com/rosegaipnazarova/ARLON.git .
            else
              git pull origin main
            fi
            
            # PM2 ishlab turgan bo'lsa to'xtatamiz
            pm2 stop all || true
            
            # Docker konteynerlarini yangilaymiz
            docker compose down || true
            docker compose up -d --build